### ISSUE TITLE
delta between sessions

### ISSUE THREAD

**Issue by boryeumao** [tasket/wyng-backup#111]
For a few good-sized volumes, I'd like to be able to get changed/new files in a session relative to an older one, without "receiv'ing" the sessions first.  Maybe this has been covered in existing issues? otherwise is this possible (maybe a pointer to where to look)?  Thanks.

**Comment by tasket** [comment]
@boryeumao Yes this would be a duplicate of issue #16 as there is no decent way to access a volume's filesystem other than mounting it, so creating a FUSE module to access Wyng archives would be the way to go.

**Comment by boryeumao** [comment]
Got it - thanks
