### ISSUE TITLE
using --tag=tagname causes error

### ISSUE THREAD

**Issue by AnounIssues** [tasket/wyng-backup#149]
sing --tag fails
i tried any possible style like --tag=test,exp --tag=test[,fff] --tag="" (and entering name in the console )
all give the same result
root@dom0 wyng]# ./wyng send vm-personal-private --tag=test Wyng 0.3.11 release 20230206 Preparing snapshots... Pairing snapshot for vm-personal-private Traceback (most recent call last): File "./wyng", line 3020, in <module> monitor_send(datavols, selected_vols, monitor_only=False) File "./wyng", line 1826, in monitor_send tag = aset.Volume.Ses.tag_parse(tag_opt, delim=",") TypeError: tag_parse() missing 1 required positional argument: 'tag' 

from a quick google it seems aset.Volume.Ses is not an instance of class (probably using ClassName instead of ClassName()) somewhere in the code

i use /wybackup folder (internal storange ) if it differs
i also tried "wyng add VOLNAME" before trying "wyng send VOLNAME --tag=test", no difference

**Comment by tasket** [comment]
@AnounIssues Thanks for reporting this bug.  Your assessment is basically correct because _tag_parse_ wasn't intended to be an instance method.

The fix is on lines 339 and 352:
```
diff --git a/wyng b/wyng
index 42a94ee..1640a71 100755
--- a/wyng
+++ b/wyng
@@ -336,7 +336,7 @@ class ArchiveSet:
                             vname = vname.strip()    ; value = value.strip()
                             if value == "none":   value = "None"
                             if vname == "tag":
-                                self.tag_add(self.tag_parse(value))
+                                self.tag_add(volume.Ses.tag_parse(value))
                                 continue
 
                             setattr(self, vname, 
@@ -349,7 +349,7 @@ class ArchiveSet:
                 for tag in addtags:   self.tag_add(tag)
 
 
-            def tag_parse(self, tag, delim=" "):
+            def tag_parse(tag, delim=" "):
                 parts = "".join(filter(str.isprintable, tag.strip())).split(delim, maxsplit=1)
                 tag_id = parts[0].strip().lower()    ; result = tuple()
                 if len(tag_id) > tag_len:
```

**Comment by tasket** [comment]
@AnounIssues Fixed in master branch.
