### ISSUE TITLE
v04 alpha3 testing issues

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#153]
### _This is for discussing errors and other problems encountered while testing/using the 04alpha3 branch..._

**Comment by boryeumao** [comment]
v04 alpha3 is not intended to recognize alpha2 archives (with '--dest' and '--meta-dir'), and separate archives are to be initialized, yes?  Please confirm - thank you.

**Comment by boryeumao** [comment]
I have some v04 alpha2 archives that seem to be working ok but are not recognized by alpha3 (with '--dest' and '--meta-dir') - are separate archives to be initialized for alpha3?  if not, perhaps I need to double-check the alpha2 archives to be sure they are properly set up?  Please advise - thank you.

**Comment by tasket** [comment]
Hi @boryeumao , 

Most people who used --meta-dir in the past can stop using it from alpha3 onward because the new version automatically keeps metadata from different archives separate.  So that option only helps if you have a peculiar issue with info being stored in /var/cache.

Not seeing alpha2 archives:  The old `--dest` URL used with prior versions won't work because Wyng no longer adds its own top-level dirs to the path.  So at the end of the URL the directory '/home/user' should become '/home/user/wyng.backup040/default'.

Or you could rename 'wyng.backup040/default' to 'mylaptop-backup' or something else and adjust the --dest URL accordingly.

**Comment by boryeumao** [comment]
Got it - the archives are now visible after adjusting _--dest_ Thank you!!

**Comment by boryeumao** [comment]
Here is the log file...
[wyng-04alpha3.log](https://github.com/tasket/wyng-backup/files/11202407/wyng-04alpha3.log)

**Comment by tasket** [comment]
@boryeumao It appears to be looking for an encrypted vi.dat file, despite the archive being un-encrypted.  Should have a fix within an hour.

**Comment by tasket** [comment]
@boryeumao A fix has been pushed to 04alpha3 branch.

**Comment by tasket** [comment]
If you need reassurances about archive integrity after encountering a bug/crash, I'd recommend running `wyng diff` commands occasionally on your volumes.  Diff not only performs hash-checking, but also checks the archive data directly against the local disk.

**Comment by boryeumao** [comment]
Thanks for the tip.  Yes indeed I've had an archive going sideways a few days ago when first trying out alpha3 (before the _vi.dat_ fix).  In subsequent attempts to work out of the jam, one situation I encountered for _send_ is the message:  "Skipping Volume; LV snapshot is from a different archive" (from alpha2, and for alpha3: without 'LV' in the message) - I assume that this means that if a volume is already wyng-backup'd in one archive it can't be sent to another one? If yes, it must be so by design and I wonder how/where the information of a local volume already in wyng-backup system is stored, or if no, perhaps the message points to something in the archive setup that I need to check?  My apologies for these questions, which are not strictly alpha3-related but would help with my better understanding - please send me on to any place where I could read up on related topics - Thanks again.

**Comment by tasket** [comment]
@boryeumao 

> I assume that this means that if a volume is already wyng-backup'd in one archive it can't be sent to another one?

That is the default.  Use `send --remap` to override it.  However, when you do that you will lose the metadata speed boost during that session because the whole volume must be scanned again to find changes.

Wyng creates snapshots to keep track of what has changed and it can't use a snapshot that references one archive to update a different archive.  If Wyng didn't require a --remap process, the resulting incremental backups would become corrupted.

One workaround for this is to create your own snapshot of the volume in question, and send that one instead to the second archive.  It requires a little extra planning on your part (you need to re-create the snapshot whenever you want to update the archive), but the benefit is that --remap is no longer necessary and neither of the volumes have to go through a full scan when you `send` to different archives.

You may be wondering if Wyng were changed to automatically keep multiple snapshots of a volume, would this issue go away?  The answer would be 'Yes', but then a host of new problems would arise.  For now, it is simpler and cleaner to display a warning and skip those volumes until user decides to remap.

**Comment by tasket** [comment]
@boryeumao BTW, if all you want to do is keep a duplicate copy of an archive, you don't have to use `wyng send`.  Its simpler in that case to use `rsync -aH --delete`.

**Comment by boryeumao** [comment]
@tasket OK I am getting a much better picture now from your explanations.  I did notice those tick snapshots back when first started using wyng-backup, but didn't connect them with the issue of multiple archives, until now.  Also your comment on using **rsync** preempted my would-be follow up question - thanks for that too :)

**Comment by boryeumao** [comment]
@tasket OK I am getting a much better picture now from your explanations. I did notice those tick snapshots back when first started using wyng-backup, but didn't connect them with the issue of multiple archives, until now. Also your comment on using ```rsync``` preempted my would-be follow up question - thanks for that too :)

**Comment by boryeumao** [comment]
My old alpha2 archive now restored, I am pushing on with alpha3.  Here is a progress report.
[wyng-04alpha3__1.log](https://github.com/tasket/wyng-backup/files/11219569/wyng-04alpha3__1.log)

**Comment by boryeumao** [comment]
My old alpha2 archive restored, I am pushing on with alpha3.  A progress report is attached.  Thanks.
[wyng-04alpha3__1.log](https://github.com/tasket/wyng-backup/files/11219726/wyng-04alpha3__1.log)

**Comment by boryeumao** [comment]
With the old alpha2 archive restored, I am pushing on with alpha3. A progress report is attached. Thanks.
[wyng-04alpha3__1.log](https://github.com/tasket/wyng-backup/files/11219737/wyng-04alpha3__1.log)

**Comment by boryeumao** [comment]
@tasket With old alpha2 archive restored, I am pushing on with alpha3.  A progress report is attached.  Thanks.
[wyng-04alpha3__1.log](https://github.com/tasket/wyng-backup/files/11219871/wyng-04alpha3__1.log)

**Comment by boryeumao** [comment]
Hi @tasket 
With old alpha2 directory restored, I am continuing with alpha3.  Something is quite puzzling with ```list``` : it works sometimes but I just can't figure out why - perhaps the error messages are meaningful enough for you to help me?  Thank you.
[wyng-04alpha3__1.log](https://github.com/tasket/wyng-backup/files/11220244/wyng-04alpha3__1.log)

**Comment by tasket** [comment]
@boryeumao The update from 2 days ago (version should say '20230411') should fix these problems.

**Comment by boryeumao** [comment]
@tasket  Yes! it most certainly does - Thank You!!  
Lost track of where ```wyng``` executables are kept (YIKES :-1:), though I did check high and low but the one thing (their file date) that would've saved the terrible embarrassment, and me from wasting your valuable time on this.  Please consider both log files from last night retracted.

**Comment by gdiShun** [comment]
Pretty much every command is netting this error with the current 04alpha3. You can kind of 'push through' after `arch-init` but everything I've tried gives this error.
```
╰─┤16:14:35├─➤sudo wyng4 arch-init --local=vg0/p0 --dest=file:/run/mount/Backups/Wyng/TEST --dest-name=Wyng --encrypt=off
Wyng 0.4alpha3 release 20230507
Naming this URL 'Wyng'.

Encryption    : off (off)
Hashing       : blake2b
Compression   : zstd:3
Traceback (most recent call last):
  File "/home/richard/.local/bin/wyng4", line 4222, in <module>
    aset    = get_configs(options)    ; dest = aset.dest
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.local/bin/wyng4", line 1725, in get_configs
    arch_init(ArchiveSet(tmpdir, dest), opts)
  File "/home/richard/.local/bin/wyng4", line 1612, in arch_init
    update_dest(aset, pathlist=[aset.confname, aset.confname+".salt", "salt.bak"])
  File "/home/richard/.local/bin/wyng4", line 2250, in update_dest
    do_exec([[CP.tar,"-cf","-","--no-recursion","--verbatim-files-from","--files-from", "-"],
  File "/home/richard/.local/bin/wyng4", line 2197, in do_exec
    raise SPr.CalledProcessError(err.returncode, err.args)
subprocess.CalledProcessError: Command '['/bin/sh', '/tmp/wyngmfd7nqdk/rpc/tmpc_ku74k1']' returned non-zero exit status 2.
```

**Comment by tasket** [comment]
@gdiShun Hi... If you add the `--debug` option to wyng it should leave some error logs under /tmp/wyng.  This will show any error messages from the called process (which will be the `tar` command, in this case).

**Comment by tasket** [comment]
@gdiShun My apologies, the name of the directory is '/tmp/wyng-debug' not '/tmp/wyng'.

**Comment by gdiShun** [comment]
Sorry for the delay.
Found this err.log in a /tmp/wyngXYZ123 folder, no wyng-debug at all though.
```
--+--
/bin/tar: archive.ini.salt: Cannot stat: No such file or directory
/bin/tar: salt.bak: Cannot stat: No such file or directory
/bin/tar: Exiting with failure status due to previous errors
tar: archive.ini: Cannot change ownership to uid 0, gid 0: Permission denied
tar: Exiting with failure status due to previous errors
```
And [here](https://i.imgur.com/zHAUxyF.png)'s an image of it. The left side directory is NOT refreshed so it's not in sync with the terminal. If I were to refresh the folder would be gone. It seems to be deleting the files early. The added 'waiting's were `input()`s put in by me to try to catch the file changes. The 2nd one is right before the 2 blocks at 2197. The files are still there at that point.

**Comment by tasket** [comment]
What is the OS distro & version?  Seems fine on Debian 11 and Fedora 37.

With encryption turned off, its normal to only have the one 'archive.ini' file. Tar will look for the other two files but that should be OK.  The first 3 lines are normal tar output, but the last 2 are not:

```
tar: archive.ini: Cannot change ownership to uid 0, gid 0: Permission denied
tar: Exiting with failure status due to previous errors
```

This is whats halting the program.  There is something, perhaps in your backup filesystem config, that is preventing tar from setting permissions as root.  You could test that by creating some files in '/run/mount/Backups/Wyng' as root and then `ls -l` to see whether they are owned as _root:root_.

An even better test would be to become root using `su -` or `sudo su -`, go to the root home, create a file there, `tar` it, then try to extract it in '/run/mount/Backups/Wyng'.  You'll probably see the same tar error.  In that case, adding an option like `--no-same-owner` may prevent the error.

**Comment by gdiShun** [comment]
Oh god. I always waste your time with stupid shit. I'm sorry.
I had a very similar issue in 0.3 with pruning. `--no-same-owner` fixed it for that. And it seems to have fixed it with this. `arch-init` completed at least. The mount is actually an SSHFS.
I am so sorry.

**Comment by tasket** [comment]
I hope I didn't imply it was stupid; I don't think it is.  Since posting my last comment I searched a bit and noticed some networked filesystems (like NFS) add this type of restriction.

So the upshot of this is I'll probably add `--no-same-owner` to Wyng so it can work under such conditions.  Thanks for reporting the error!

**Comment by gdiShun** [comment]
Oh no. It wasn't anything you said. It was just me beating myself up. When I realized it was something I already previously fixed for myself... and how basic of a thing it is... But I guess it's good to have it out there for anyone else in this very niche scenario. lol

Thank you for the help.

**Comment by gdiShun** [comment]
Now to change the topic to some (maybe) actual bug reports now. :sweat_smile:  I don't have the logs this time. Sorry. 

IIRC trying to send without a tag description(assuming they're still intended to be optional) will give a List Index error. It assumes `tags[1]` exists IIRC. If you fix that, it'll later assume `parts[1]` exists. Didn't try to fix that.

Trying to prune with tags will give like a type error I think. Something like `x.tags` does not exist because it's a string object. I think maybe `vol.tags` is what you wanted?

Not sure if this is a bug or perhaps a product of the encryption but it's not possible to mount volname.tick like you could in 0.3. I think it complains about bad superblocks or something.

Lastly, a question. If there's an error, or you Ctrl+C out while Wyng is running, there can be timestamp mis-matches, or something along those lines. It basically completely locks down Wyng. What is the correct way to deal with those?

Thank you.

**Comment by tasket** [comment]
@gdiShun 

1. OK, I'll look into the tag handling.

2. I don't think an error like that should be happening.  Wyng doesn't write directly to .tick snapshots; the only thing it does to them (besides creating them) is add lvm tags and set the snapshots to _read-only_ (and they are not supposed to be used/accessed for any other purpose than Wyng's delta scans... any change to a .tick at all, such as from mounting it as writable, could lead to corrupted backups).  You might want to make a snapshot of the snapshot and set it to _read-write_ mode and see if that works.  If it doesn't work and the snapshot appears un-mountable or otherwise corrupt, but the original volume is still OK, then you should `lvremove` the .tick and do a `send --remap` of that volume.

3. Yes, this is a temporary issue created in the alpha.  You can delete '/var/cache/wyng', or even better just update to the version I pushed to 04alpha3 yesterday which now has code to resolve common cache/timestamp mismatches automatically.

**Comment by eric-blabla** [comment]
if I would like to restrict the ssh access, which commands do I need to allow remotely in order that WYNG still works ?

**Comment by eric-blabla** [comment]
I tried to backup one vm 'work'

```
[root@dom0 ~]# ./wyng  arch-init --local qubes_dom0/vm-pool --dest=qubes-ssh://work:user@WYNGSERVER:/somepath 
Wyng 0.4alpha3 release 20230531
Enter new encryption passphrase: 
Re-enter passphrase:
Done. 
```
Then something unexpected happened:
```
[root@dom0 ~]# ./wyng add vm-work-private --dest=qubes-ssh://work:user@WYNGSERVER:/path 
Wyng 0.4alpha3 release 20230531
xmodmap:  unable to open display ''
Enter passphrase: 

[root@dom0 ~]# ./wyng send --dest=qubes-ssh://work:user@WYNGSERVER:/path 
Wyng 0.4alpha3 release 20230531
Enter passphrase: 
Encrypted archive: qubes-ssh://work:user@WYNGSERVER:/path 
Last updated 2023-06-07 14:07:25.437818 (+02:00)

Preparing snapshots...
  Skipping vm-work-private; snapshot is from a different archive.
No new data

```

Does the fact that I backup data on a local drive prevent from backing up via SSH?
Or do I need to power down the VM before backup?

**Comment by tasket** [comment]
@eric-blabla 

> Does the fact that I backup data on a local drive prevent from backing up via SSH?

If a volume has a Wyng snapshot associated with a different archive, Wyng won't automatically overwrite that snapshot to write to the new archive.  Two things you can do:

1. Use `--remap` with `send`.  That allows Wyng to overwrite an existing snapshot from a different archive.  The side effect is that when the remap/overwrite happens, the backup speed for that volume will become ordinary (metadata cannot be used to accelerate the backup during that backup session).
2. Or keep a clone of that VM.  Send the original to archive 1, and send the clone to archive 2.  That works without remap because each original volume has a separate Wyng snapshot.

You could also simply refrain from sending a single volume/VM to multiple archives.

For testing purposes, its good to test --remap on occasion, but alternating that volume back and forth between two archives all the time is not a good idea because it slows you down and it skips Wyng's delta mapping code which is important to test.

---

> the qube that holds the ssh-key must have network acces

Yes.  However, for security I'd recommend using a VM dedicated to ssh, instead of a VM like 'work'.  This is similar to the idea of dedicating a VM to handle VPN access.  You can configure an ssh VM to use very little RAM (350MB is fine) and disk space, and there is also a way to configure a VM so it shuts down automatically after being idle.

**Comment by tasket** [comment]
Note:  The 04alpha3 branch is closing down.  Please log individual issues when using the beta version.

Thanks!

**Comment by tasket** [comment]
Several bug fixes just landed in 08wip.  This is about all I anticipate, although there is one more possible issue with `prune --all-before` not getting date selection quite right (off by 1).  I'm looking into it now.
