### ISSUE TITLE
Unattended flag should be set automatically

### ISSUE THREAD

**Issue by keeperofdakeys** [tasket/wyng-backup#160]
Currently wyng requires the unattended flag to be set manually for some operations to successfully run from scripts or cron. If the user isn't aware of this, it can lead to scripts or cronjobs not running an operation when intended. This feels like a UX bug.

The unattended flag can be set automatically by checking if stdin is a tty, like this https://rosettacode.org/wiki/Check_input_device_is_a_terminal#Python.

**Comment by tasket** [comment]
Thanks!  This has been implemented.
