### ISSUE TITLE
Add encryption option using keyed-hash of existing digests

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#161]
### Proposal

For nonce generation, implement  `Hk( rnd || pthash )` as a higher-performance alternative to `Hk( rnd || m )`.

A subkey would be dedicated for this purpose, as in the alpha3 implementation of _xchacha20-t3_.

### Rationale

Wyng already generates 256-bit cryptographic hashes of plaintext (meta)data for various uses such as deduplication.  So, to attain both security and speed, it may be advantageous to use existing hashes to generate nonces in a reuse-resistant method that is similar to the libsodium recommendation used in #159.

HMAC itself demonstrates that hashing a hash with an additional factor (a key) can be robustly secure for generating nonces, as libsodium recommends HMAC for this purpose.

Further, it may be that libsodium did not recommend this method because it would be odd to assume an application would already have a supply of suitable hashes available.  Most applications would only begin making cryptographic hashes of data when adding encryption, so Wyng is unusual in this respect.

### Safeguards

* It may be necessary to disable encryption modes incorporating _pthash_ when the user selects an unsuitable Wyng hash mode such as SHA256, or vice-versa.

* Using the same hash function as the _pthash_ source may be best, i.e. BLAKE2b.

### Other considerations

Having a deterministic mode (see #157) available may be desirable to some users, in which case another alternative could be to generate nonces similar to the above method but without the random prefix, for example  `Hk( pthash )`.

---

**CC:** @demimarie

**Comment by DemiMarie** [comment]
This is fine with me!

**Comment by tasket** [comment]
Borrowing the test table from 159, I have a new benchmark to add...

| Runtime (sec) | Wyng Encryption Mode | Nonce Method |
|------------:|-----|--------------------------|
| 68.7   | xchacha20 | XChaCha20 concat counter |
| 83.8   | xchacha20-t1 | XChaCha20 BLAKE2b Hk(rnd\|\|m) |
| 68.0   | xchacha20-t2 | XChaCha20 rnd nonce |
| 76.3   | xchacha20-t3 | XChaCha20 HMAC-SHA256 Hk(rnd\|\|m)* |
| 68.5   | n/a                   | XChaCha20 BLAKE2b Hk(rnd\|\|pthash) |
| 60.0   | n/a  (-t4?)        | XChaCha20 HMAC-SHA256 Hk(rnd\|\|pthash) _where pthash is also from HMAC-SHA256_|

Generating the manifest hashes with HMAC-SHA256 yields a 12.5% speed boost over the fastest BLAKE2b result (these figures do not include actually sending the data, just reading & encoding).

The question is whether HMAC can be securely used this way.  Reading up on HMAC's properties, it seems like it would OK as long as the hashing key was kept secret.  Also, some thought should be given to properly deriving the key.

**Comment by tasket** [comment]
This mode has been implemented as _'xchacha20-t4'_.   The resulting archive will be configured to use the -t4 handler which uses manifest hashes for data nonces, but uses the -t3 handler for metadata since the metadata is not speed-critical and -t3 allows simpler metadata code.

Further, the data hashing algorithm is now specifically using HMAC-SHA256 based on a secret subkey, and this applies across all the testing modes that are still user-selectable.  As a result, if you created older -t2 or -t3 archives their data will no longer be recognized as valid!  __You are urged to create new -t2 and -t3 archives in that case__.

(If you created archives under the old default _xchacha20_, they will still be handled the same way and data recognized as valid.  A counter mode is still select-able as _xchacha20-tc_ which now uses HMAC for data hashing.)

Switching the hash functions to HMAC has made `send` significantly faster for all select-able modes.  Some current benchmark-mode times (12GB volume data):

| Runtime (sec) | Wyng Encryption Mode | Nonce Method |
|------------:|-----|--------------------------|
| 59.3   | xchacha20-tc | XChaCha20 counter nonce |
| 58.4   | xchacha20-t2 | XChaCha20 rnd nonce |
| 66.1   | xchacha20-t3 | XChaCha20 HMAC-SHA256 Hk(rnd\|\|m)* |
| 58.6   | xchacha20-t4 | XChaCha20 HMAC-SHA256 Hk(rnd\|\|pthash) |

This is a great pay-off for relatively few engineering changes that stay within safe, recommended norms.  I don't see a need at this point to try any additional new modes.

**Comment by tasket** [comment]
An extra precaution was added to make the subkeys more robust.  Their size has been increased to 512 bits and they now have independent 512 bit salts (slots 2 and 3) and separate contexts and separate iterations within those contexts.  The subkey hash algorithm has also been changed to _SHA-512_.  Primary keys (slots 0 and 1) now use 512 bit salts as well.  This is being done to ensure ample key differentiation and strength.

This change also means if you were using any of the _-tX_ encryption modes, those archives won't work with Wyng version 20230528 onward ...again.  (Sorry about that!)

**Comment by tasket** [comment]
The encryption mode selection names have been decided.  Here is a quick rundown of the changes:

Deprecated:

_xchacha20_ — This is the original counter mode, which is replaced by slightly better counter mode below.  This mode will continue to function for existing archives.

Removed:

_xchacha20-t1_ and _xchacha20-t2_ — No longer present in code.

Accepted:

_xchacha20-t3_, _xchacha20-t4_ and _xchacha20-tc_ — These modes have been renamed _xchacha20-msr_, _xchacha20-dgr_ and _xchacha20-ct_, respectively.  The last option is the name going forward for the protected counter mode.

Also, the default encryption setting will be _xchacha20-dgr_, which uses the 'Hk || rnd' amalgam for generating nonces under the _data_ key and the simpler-to-implement but slower 'm || rnd' for _metadata_.
