### ISSUE TITLE
Error when using `send` with `--autoprune`

### ISSUE THREAD

**Issue by de-souza** [tasket/wyng-backup#170]
Hi, when using using `send` with the `--autoprune` option, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 4635, in <module>
    monitor_send(storage, aset, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 3368, in monitor_send
    for vol in aset.vols:   autoprune(vol, apmode="full")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wyng", line 3544, in autoprune
    if len(vol.sesnames) < 2:   return False
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'sesnames'
```

Using `send` towards a newly-created archive works, but if I use the `--autoprune` option I get this error when I try to `send` a second time.

- OS: [Qubes 4.2.0-rc1](https://www.qubes-os.org/news/2023/06/02/qubes-os-4-2-0-rc1-available-for-testing/) with a BTRFS filesystem
- Wyng version: [Wyng 0.8beta release 20230802](https://github.com/tasket/wyng-backup/tree/3921893)

**Comment by tasket** [comment]
@de-souza  Thanks for reporting this!  A fix has been posted to the main branch.
