### ISSUE TITLE
Automated password and passphrase input

### ISSUE THREAD

**Issue by gangamstyle** [tasket/wyng-backup#171]
My attempt to migrate from wyng 0.3 to a latest version has terribly failed due to misunderstanding on how to provide non-interactive password to wyng.

So how to provide password to wyng to make auto-backup from script ? ENV variable ? config ?
It is insane to enter it each time by hand!

**Comment by tasket** [comment]
@gangamstyle Wyng is designed so that the passphrase prompt will always come first.  Directing the passphrase to Wyng's standard input will work.

Also check out the `--authmin` option which reduces the number of times you have to enter the passphrase.

**Comment by tasket** [comment]
I see that using getpass() creates a problem for piped input.  Looking into it now...

**Comment by tasket** [comment]
@gangamstyle A fix has been posted to the '08wip' branch.  This should allow sending passphrase over piped/redirected input.

**Comment by gangamstyle** [comment]
Thanks, I tried stdin before and right now it should be fixed.
But, until it is beta and API is flexible, please consider using industry standard for session management: environment variables. It is supported by everything (linux, windows).
Borg API is a good example, it is stable and simple: https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables

**Comment by tasket** [comment]
OK, I have pushed the fix to the main (beta) branch.

Thanks for the suggestion.  I'll consider adding support for some parameters via env vars, although I do not expect them to proliferate much in the near term.  You may want to see issue #118 which is to support a Python module API for Wyng.

**Comment by de-souza** [comment]
I had this issue as well and I can confim that the [last commit](https://github.com/tasket/wyng-backup/tree/6e2cc69) fixed it.
