### ISSUE TITLE
wyng/wyng-util-qubes: sparse/sparse-write restore/receive operations broken (0.7beta 20230721 with wyng 0.8beta 20230826)

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#174]
![signal-2023-09-19-105347](https://github.com/tasket/wyng-backup/assets/827570/7f369931-9366-41b1-b2b5-bf4610d28573)

~a call without -w sparse/-w sparse-write from wyng-util-qubes works.~
All restore operations from wynt-util-qubes currently broken with 0.7beta 20230721 and wyng 0.8beta 20230826.

**Comment by tlaurion** [comment]
![signal-2023-09-19-110222](https://github.com/tasket/wyng-backup/assets/827570/fb391d39-9d08-4bd0-ad10-eb47e783305f)

restore all operations from wyng-util-qubes do not seem to work. Modifying title

**Comment by tasket** [comment]
@tlaurion Fixes in 08wip branch.

**Comment by tasket** [comment]
@tlaurion Well, I thought that fixed it, but apparently not.

**Comment by tasket** [comment]
@tlaurion It should be good now.
