### ISSUE TITLE
qubes-ssh port is not respected?

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#191]
Testing against openwrt hosting ssh hidden tor service I can reach from qube doing qube-ssh, but dom0 cannot use it?

```
(5)$ time sudo wyng-util-qubes --dest qubes-ssh://wyng-wdcloud:root@redactedhiddentoraddress.onion:2345/mnt/Backups/nv41 --dedup -wremap --authmin 1080 backup wyng-wdcloud
wyng-util-qubes v0.9beta rel 20240424
Wyng 0.8wip release 20240507
CalledProcessError(255, [['/usr/bin/qvm-run', '--no-color-stderr', '--no-color-output', '-p', 'wyng-wdcloud', '/usr/bin/ssh -x -o ControlPath=~/.ssh/controlsocket-%r@%h-%p -o ControlMaster=auto -o ControlPersist=60 -o ServerAliveInterval=30 -o ConnectTimeout=30 -o Compression=no root@redactedhiddentoraddress.onion "$(/usr/bin/cat /tmp/wyngrpc/tmpyjx13_70)"'], ['/usr/bin/cat', '-v'], ['/usr/bin/tail', '--bytes=2000']])

ssh: connect to host redactedhiddentoraddress.onion port 22: Connection refused^M
[0, 255]

Destination not ready to receive commands.
```

Seems like the port is not passed through ssh options @tasket ?

**Comment by tlaurion** [comment]
I'm that close to create a guide, first for my own setup reference, with openwrt having usb hotpluggable drives with raid5 with 4 cheap ssd drives connected.

Works locally with qube:, works remotely with qube-ssh, but when swithing template to whonix-wks-17 to use my router's hidden ssh server on port 2345 above, nope.

That would be ideal for me when wanting to "connect back home" and upload diff backups as I go, even over phone tethered wifi, with qubes+whonix doing the magic to talk with my openwrt configured hidden tor ssh service.

I think a well redacted guide to reproduce such setup would permit self-hosters to replicate such setup without needing to trust anyone else but themselves in the goal of iterating and mitigating #21 #91 as of now.

**Comment by tlaurion** [comment]
Hmmm

https://github.com/tasket/wyng-backup/blob/08177d45133d178a1f3b289b0e1c02d40d0076ae/src/wyng#L2176-L2182

**Comment by tasket** [comment]
@tlaurion This should be fixed; its working for me now.
