### ISSUE TITLE
615: SyntaxWarning: invalid escape sequence '\^'

### ISSUE THREAD

**Issue by averyfreeman** [tasket/wyng-backup#200]
Action: 
Invoking the `wyng` executable from the command line without any commands or options flags.

Expected result: 
`wyng` delivering a help menu in a way in which it demonstrates it is reliable enough to use for further tasks.

Actual result:
Getting this warning when running `wyng`:

```bash
$ sudo wyng
/usr/bin/wyng:615: SyntaxWarning: invalid escape sequence '\^'
  if re.match(".*[,=\^]", tag_id) or any(map(str.isspace, tag_id)) \
```

If the line numbers match the error output, it's related to this for loop:

```python
            with io.StringIO(arch.decompress(buf).decode("UTF-8")) as sf:
                for ln in sf:  # line 615
                    vname, value = map(str.strip, ln.split("=", maxsplit=1))
                    if vname == "tag":
                        self.tag_add(ArchiveSession.tag_parse(value))
                        continue
```
Other information:
My distro system Python version is 3.12.3.  If I invoke `wyng` in a Python 3.9.9 virtualenv, I don't see this error.  

Test environment:
```zsh
OS: Arch Linux x86_64
Host: Precision 7730
Kernel: Linux 6.9.1-zen1-1-zen
Uptime: 1 day, 12 hours, 11 mins
Packages: 2159 (pacman), 86 (flatpak-user), 11 (brew)
Shell: zsh 5.9
Display (LG 32 FHD): 1920x1080 @ 60Hz *
Display (CMN1738): 1920x1080 @ 60Hz
DE: Gnome 46.1
WM: Mutter (X11)
CPU: Intel(R) Core(TM) i7-8750H (12) @ 4.10 GHz
Memory: 14.78 GiB / 31.12 GiB (48%)
Swap: Disabled
Disk (/): 115.20 GiB / 889.57 GiB (13%) - xfs
Disk (/home): 418.57 GiB / 874.96 GiB (48%) - ext4
Locale: en_US.UTF-8

**Comment by tasket** [comment]
OK, thanks for the heads-up.  Up to this point I've tested Wyng with CPython versions 3.8 through 3.11, so I'll have to look into this further in a bit. Probably I'll install 3.12 from Debian Testing.

**Comment by averyfreeman** [comment]
Thanks! For now I'll test it in a venv

**Comment by tasket** [comment]
@averyfreeman Could you try changing the line below in _def tag_parse()_

```
  if re.match(".*[,=\^]", tag_id) or any(map(str.isspace, tag_id)) \
```

to add an 'r' before the quote like this:

```
  if re.match(r".*[,=\^]", tag_id) or any(map(str.isspace, tag_id)) \
```

**Comment by tasket** [comment]
Tested on Ubuntu 24.04 (CPython 3.12.3).
