### ISSUE TITLE
Change repository passphrase

### ISSUE THREAD

**Issue by rapenne-s** [tasket/wyng-backup#216]
Hello,

I wondered if it was possible to change the repo passphrase once it's created?

**Comment by tasket** [comment]
@rapenne-s No, unfortunately that is still a todo for a future version, issue #198  

There is currently no actual key or passphrase stored anywhere, only the key that is synthesized by scrypt at runtime using the passphrase input and salt.  So the only practical advice using the current Wyng version is to start a new archive.
