### ISSUE TITLE
Remaking archive fails

### ISSUE THREAD

**Issue by Eric678** [tasket/wyng-backup#219]
If one decides one made a mistake making a new archive, removing it and remaking it creates a corrupt archive...
```
[root@dom0 ~]# wyng arch-init --dest=file:/tmp/w
Wyng 0.8 beta release 20240827
Enter new encryption passphrase: 
Re-enter passphrase: 

Encryption    : xchacha20-dgr (xchacha20-poly1305-msr)
Data Hashing  : hmac-sha256
Compression   : zstd:3
Done.
[root@dom0 ~]# wyng list --dest=file:/tmp/w
Wyng 0.8 beta release 20240827
Enter passphrase: 
Encrypted archive 'file:/tmp/w'
Last updated 2024-11-04 ...

No volumes.
[root@dom0 ~]# rm -rf /tmp/w
[root@dom0 ~]# wyng arch-init --dest=file:/tmp/w
Wyng 0.8 beta release 20240827
Enter new encryption passphrase:
Re-enter passphrase:

Encryption    : xchacha20-dgr (xchacha20-poly1305-msr)
Data Hashing  : hmac-sha256
Compression   : zstd:3
Done.
[root@dom0 ~]# wyng list --dest=file:/tmp/w
Wyng 0.8 beta release 20240827
Error: Could not decrypt/authenticate archive.
```
Waiting a while stops the issue - perhaps arch-init needs to clear the entry in /tmp once it has decided it can go ahead.

Which does bring up another issue - I cannot see any way to list the setup parameters that were used on an existing archive.
Not in clear text at top of archive.  Perhaps add to `list --all` output?

**Comment by tasket** [comment]
The new archive isn't corrupt. This error is from the caching of the authentication token; the old one sits in memory for a while unless you tell Wyng to forget it. 

A workaround is to use `--authmin=-1` the first time you access the new archive.

**Comment by Eric678** [comment]
OK, that crystalises this issue into 4:
1. Misleading error message
2. arch-init does not write the cache in 'memory' like other commands, which causes
3. Annoying bug that the passphrase has to be entered a 3rd time after an arch-init
4. No way to find out init config of archive

**Comment by tasket** [comment]
Its not clear to me that arch-init should ever cache an auth. Standard practice with authentication is to avoid this, so accessing the archive after creation should require second entry of passphrase.

The archive config can be seen if its decrypted.  Otherwise, only the encryption mode is known.

**Comment by tasket** [comment]
Fix pushed to 08wip
