### ISSUE TITLE
Restoring backup of a block device fails

### ISSUE THREAD

**Issue by Eric678** [tasket/wyng-backup#220]
Adding an import-other volume from a block device appears to work OK.
When it comes time to restore that backup to the block device:
```
# wyng receive efi --save-to=/dev/sda1 --dest=qubes://...
Wyng 0.8 beta release 20240827
Encrypted archive 'qubes://...'
Last updated 2024-10-27 17:29:05.936196

Warning:  Receiving to existing volumes will overwrite them!
Are you sure? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 5168, in <module>
    count = receive_volume(storage, aset.vols[dv], select_ses=options.session or "",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wyng", line 4344, in receive_volume
    punch_hole = save_storage.block_discard_chunk
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'block_discard_chunk'
```

**Comment by tasket** [comment]
The `--save-to` option strongly assumes the destination is a file. That should be fixed to allow block devices.

Temporary workaround is to receive to a file, then `dd` the file contents to the block device.

**Comment by tlaurion** [comment]
Looking for a solution to this problem. Having a mechanism  to restore /boot and dom0 is desperately needed, even better if both at the same time.

**Comment by tasket** [comment]
Fix pushed to 08wip @Eric678 @tlaurion

**Comment by tlaurion** [comment]
> Fix pushed to 08wip @Eric678 @tlaurion 

@tasket ping https://github.com/tasket/wyng-backup/issues/31#issuecomment-1724744489

**Comment by tasket** [comment]
Closing this as fixed.
