### ISSUE TITLE
keep comments in sparsebak.ini when using delete/add commands

### ISSUE THREAD

**Issue by taradiddles** [tasket/wyng-backup#29]
If feasible/easy to implement, it'd be nice to keep comments in sparsebak.ini when the file is rewritten (eg. after using `add`/`delete` commands).
If it isn't, maybe add a static top comment that user comments will be deleted when the file gets rewritten ?

And/or create a backup .ini file ?

**Comment by tasket** [comment]
This file I have less flexibility with (its managed by Python configparser), but I'll definitely look into it.

**Comment by taradiddles** [comment]
> This file I have less flexibility with (its managed by Python configparser)

Yes I saw that when looking at code so I expected that keeping comments/user formatting might not be straightforward.

I'm sure the config format will evolve when/if you add support for multiple volume groups and other stuff so it's not worth loosing time on this minor issue...

**Comment by tasket** [comment]
@taradiddles A comment/description can now be added to a volume. Its not the same as actual comment lines in the ini, but may serve a similar purpose.

Interestingly, the Python ini parser documentation says that comments beginning with '#' or ';' are supported by default.

**Comment by tasket** [comment]
Closing as this appears to be covered by current beta.
