### ISSUE TITLE
add `--quiet` etc. options to control verbosity

### ISSUE THREAD

**Issue by taradiddles** [tasket/wyng-backup#30]
The `monitor` command outputs text to stdout so on non-Qubes systems an email will likely be sent by the cron daemon each time the job is run (or /var/spool/... will silently be filled if the mta is not properly configured).

Maybe it's enough to redirect stdout to `/dev/null` but I couldn't find a way to trigger an error with `monitor` to test if errors are still shown (ie. output to stderr).

EDIT: alternatively `monitor` could not output anything at all (except warnings/errors of course) and there could be a `--verbose` option

**Comment by tasket** [comment]
Good idea.

There is already a little log-friendliness when using the `-u` unattended option. In that mode, the progress line for `send` should only update 5x instead of 1000x.

But in future (v0.3 I think) I'll switch to using the logger module and that will give normal verbosity options.

**Comment by tasket** [comment]
@taradiddles Implemented `--quiet` mode.
