### ISSUE TITLE
Explore backups for fixed LVM, non-CoW storage

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#31]
Many systems are installed with fixed (non-thin) lvm volumes and documentation suggests thin snapshots can be created for fixed volumes. If so, it may be possible to use the thin lvm tools to track deltas for fixed volumes the same way as in an all-thin environment.

The challenges for implementation are:
* Determining actual thin-tools compatibility with these hybrid snapshots.
* Tracking the fixed nature of configured volumes during archive ops, if any special steps are needed.
* Advising users on a straightforward way to configure their fixed-lvm system with a suitable thin pool.

Barring the above, it may be helpful to reference documentation showing the best practices for converting fixed-lvm systems over to thin pools, btrfs, etc.

**Comment by tasket** [comment]
After researching hybrid snapshots, there is no way to target a non-thin vol + thin snapshot consistently since the non-thin volume's state cannot be known from its metadata. The combination could easily be corrupted and Wyng would have no way to detect or compensate for it.

So I'm changing this issue to a general 'Support volumes in non-snapshot storage' theme. Such volumes would have to be added to the archive with a special option flagging them as non-CoW, and they would essentially trigger a --remap on each incremental `send`. IOW, this volume type could be supported if Wyng treated it like a traditional incremental backup, comparing all the volume data against hashes for each run.

Users should be consistently reminded of this special mode to prevent confusion about slower backup times, etc.

**Comment by tasket** [comment]
Some support for this can be added via an option like `--import-from` to enable reading volumes that sit outside of a supported snapshot storage system.  This would complement the existing `--save-to` option.

**Comment by tasket** [comment]
@tlaurion Implemented option `--import-other-from` which is to be used like this:

`wyng send --import-other-from=volname:|:path/to/file`

The char sequence ':|:' is used as a delimiter between the archive volume name and the source file path.

This requires testing.

**Comment by tlaurion** [comment]
> @tlaurion Implemented option `--import-other-from` which is to be used like this:
> 
> `wyng send --import-other-from=volname:|:path/to/file`
> 
> The char sequence ':|:' is used as a delimiter between the archive volume name and the source file path.
> 
> This requires testing.

@tasket i tried to test this today through `wyng-util-qubes -w import-other-from=boot:|:/dev/sda1` without success. Not sure what I'm missing.

**Comment by tasket** [comment]
@tlaurion TBH I haven't tested that manually from the util (although the util itself does use that wyng option).

I think what you're missing is an escape char for the vertical pipe:
```
wyng send --import-other-from=volname:\|:path/to/file
```

**Comment by tlaurion** [comment]
> wyng-util-qubes -w import-other-from=boot:|:/dev/sda1

@tasket :

```
(1)$ sudo wyng-util-qubes --dest qubes-ssh://wyng-rpi5_raid5:root@rpi5/mnt/Backups/nv41 --authmin 1080 --includes -wremap -wuse-snapshot --dedup --include-disposable=on -wtag='sys-cacher,enabled' -wtag='qusal,with sys-audio working' -wtag='daily' -wimport-other-from=boot:\|:/dev/sda1 backup
wyng-util-qubes v0.9 beta rel 20241022
Error code 1:
Wyng 0.8 wip release 20241111
Option --import-other-from may only be used with send.
```

**Comment by tasket** [comment]
@tlaurion For now, comment-out these lines starting at 5017:
```
if options.import_other_from and options.action != "send":
    x_it(1, "Option --import-other-from may only be used with send.")
```

It makes more sense if the option is just ignored when send isn't used (the util invokes some other wyng commands before sending).

**Comment by tlaurion** [comment]
> > wyng-util-qubes -w import-other-from=boot:|:/dev/sda1
> 
> @tasket :
> 
> ```
> (1)$ sudo wyng-util-qubes --dest qubes-ssh://wyng-rpi5_raid5:root@rpi5/mnt/Backups/nv41 --authmin 1080 --includes -wremap -wuse-snapshot --dedup --include-disposable=on -wtag='sys-cacher,enabled' -wtag='qusal,with sys-audio working' -wtag='daily' -wimport-other-from=boot:\|:/dev/sda1 backup
> wyng-util-qubes v0.9 beta rel 20241022
> Error code 1:
> Wyng 0.8 wip release 20241111
> Option --import-other-from may only be used with send.
> ```


This is `backup` from wyng-util-qubes, with `-wimport-other-from=boot:\|:/dev/sda1` expected to be passed and translated as send to wyng?

**Comment by tasket** [comment]
@tlaurion Yes, it gets passed to wyng. But it won't work until those two lines are removed. The updated version is in the wyng 08beta branch.

**Comment by tlaurion** [comment]
> @tlaurion Yes, it gets passed to wyng. But it won't work until those two lines are removed. The updated version is in the wyng 08beta branch.

I commented and saved boot to archive.
Note that latest commit doesn't contain the fix

**Comment by tasket** [comment]
Sorry about that. Its there now.
