### ISSUE TITLE
Make remap easier in recovery situation.

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#52]
https://github.com/tasket/wyng-backup/issues/50#issuecomment-583556414

**Comment by tasket** [comment]
Overlaps with issue #9

**Comment by tasket** [comment]
The approach I took here was to have _prepare_snapshots()_ (runs when `monitor` or `send` starts) look for the --remap option. If remap is specified it will go ahead and run the `--remap diff` procedure on any selected volume that needs it.

I think this way is better than `--all diff` bc any user wanting to specify remap "just to be sure" won't fall into a mistaken routine where they are forcing a diff all the time and then crying that wyng is super slow. Instead the diff will probably only run if wyng decides the volume requires it to make a monitor or send possible.
