### ISSUE TITLE
QubesOS "qvm-volume revert AppVM:volname" use case not managed

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#57]
wyng-backup fails on monitor and send with  `NotImplementedError: Cannot delete last session`

Starting the AppVM in question mitigates the error, while automated monitor and send fails until the reverted volume is started again.

**Comment by tasket** [comment]
I don't understand "until the reverted volume is started again." Needs elaboration.

Is this on a newly added volume (no initial session)?

**Comment by tasket** [comment]
I'm guessing "started again" means VM is started again after the qvm-volume revert.

**Comment by tasket** [comment]
@tlaurion Changes in the bfa3f0a commit and a prior commit should address this.

**Comment by tasket** [comment]
@tlaurion OK, this run of commits is done and beta4 is in good shape again. I'm going to let it rest for a couple of days.

**Comment by tasket** [comment]
Please re-open if beta4 does not resolve this issue.
