### ISSUE TITLE
Feature: offer metadatadir option

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#58]
So that wyng can look at a directory different then /var/lib/wyng.backup for metadata

**Comment by tasket** [comment]
I'll try to get this in beta4 next week.

**Comment by tlaurion** [comment]
Can't [wait](https://github.com/tasket/wyng-backup/issues/54).

**Comment by tasket** [comment]
@tlaurion Implemented in commit fa90279c23f5d306cafff16f490a2fcb824af319

**Comment by tlaurion** [comment]
#60 couldn't be resolved by this, if locking was done per metadir? (each having default directory)

**Comment by tasket** [comment]
Perhaps, but the complexity is non-trivial so I think that is one for v0.3.

**Comment by tlaurion** [comment]
@tasket : cannot be used with arch-init?

**Comment by tlaurion** [comment]
nevermind!
