### ISSUE TITLE
Feature: Tag and Comment at send / list

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#59]
So a user can track milestones in the backups outside of automatic snapshots being taken.
Would also be nice if list gave the possibility to be detailed about all the snapshots in its known metadata, and even list the ones being on the remote backup dir.

**Comment by tasket** [comment]
Putting this under v0.3 for now.

**Comment by tlaurion** [comment]
@tasket : this would be required so crontab or APIs can claim ownership of who called for the backups, while the user can identify clearly a big change he was responsible for.

**Comment by tasket** [comment]
Per online discussion, the new feature would allow recording of a tag + comment pair when sending. Tagging functionality would be limited to adding new ones and finding volume+sessions that match a tag, along with purging tags when associated sessions no longer exist in the archive.

The add function can be done in a UI mode similar to git, which launches an editor like `vi` to accept comment text.

The size of a tag and comment are TBD with input from @tlaurion

**Comment by tasket** [comment]
For max sizes, my initial suggestion for _tag_ is 40 alphanumic and _comment_ limited to 512 UTF-8. However, they'll probably need to be larger.

**Comment by tasket** [comment]
@tlaurion Initial support for tags added, `-t` can be used during `send` and `list` (but not yet with `-u`). Currently, the max sizes for tagID and description are 25 and 90 chars.

**Comment by tasket** [comment]
The option name is `--tag` instead of `-t`.

Prefix tag name with `^` carat when using tags in `--session` or `--keep`.

The new `--keep` option for `prune` can take single date-times, regular tags or the reserved tag `^all`. Using `--keep ^all` will prevent any tagged sessions from being pruned. And you can use multiple `--keep` on a command line.

**Comment by tlaurion** [comment]
@tasket opencollective needing payment information for pending transaction (I know, late. But better late then never.)
