### ISSUE TITLE
Feature: multiple backup profiles (not just default?)

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#60]
Hello there.

I see that everything wyng is under the default profile metadir (/var/lib/wyng.backup/default) and backup dirs (./wyng.backup/default) matching default profile name.

Is there a way to specify other profiles to arch-init and other operations? In what I try to accomplish, it would mean that a "local" (default) and remote (QubesOS/OEM maintained templates) could coexist under /var/lib/wyng.backup/ and permit restoration on local LVM from local/remote backups.

THAT, would be amazing.

Is QubesOS team aware of the possibilities of this tool to remove dependency on rpm to deploy templates post-install? (which doesn't respect rpm -V contract for verification post-install, anyway...). It would just be totally awesome to have QubesOS deploy those backups on a read-only ssh accessible server to users, so that users can actually restore their templates to latest releases ( with matching timestamps ) in emergency recovery situations (including [root-snapshot](#53 ) that could be moved over root from recovery,  once #18 is figured out so the user can reinject his QubesOS Machines configs inside of XML.)

[Heads](#54 ) could even permit such deployments directly from the recovery shell if network wire was connected, offering [similar detached signed digest validation](https://github.com/osresearch/heads/blob/master/initrd/bin/gui-init#L37) upon QubesOS [distribution gpg signature](https://github.com/osresearch/heads/blob/master/initrd/etc/distro/keys/qubes-4.key) of a [similar logic ](https://github.com/osresearch/heads/blob/master/initrd/etc/functions#L264) that is enforced here against user keypair, signed by QubesOS distribution key on the root of their offered ssh wyng-backup directory.

@marmarek? @tasket ?

**Comment by tasket** [comment]
There is no way to do it from wyng v0.2, although the dir structure anticipates this capability. Its already mentioned on the 'misc list' issue #25.

Swapping the default dirs manually could work, but _only_ if wyng is not scheduled to run in the background (or if you put a lock on '/var/lock/wyng').

**Comment by tasket** [comment]
This is sort-of already supported via the `--meta-dir` option. However, the way its described here won't be possible for v0.3, so I expect it to land in v0.4 instead–and probably in a more elegant form that obviates the need for users to think about local metadata storage.

**Comment by tasket** [comment]
Work has begun on this. When it leaves the 04wip branch, the file format will change (not drastically) and we'll be in alpha3.

**Comment by tasket** [comment]
Implemented in [04alpha3](https://github.com/tasket/wyng-backup/tree/04alpha3) branch.
