### ISSUE TITLE
qubes-ssh identity management / Destination not ready to receive commands

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#61]
Trying to setup this, since sshfs is having really poor performance.

```
sudo wyng --local=qubes_dom0/pool00 --meta-dir=/var/lib/test --dest=qubes-ssh://wyng-remote:wyng@sshserver/home/user/wyng/ arch-init --compression bz2
sudo wyng --meta-dir=/var/lib/test add vm-debian-10
```

results in 
```
sudo wyng --meta-dir=/var/lib/whatbox-ssh send --debug
VOLUME vm-debian-101-root None None
Destination not ready to receive commands.
```

my sshfs equivalent was setuped with a .bashrc script which was taking care of:
`ssh-add` ( no passphrase)
```
ssh-add
sudo sshfs -o allow_other,idmap=user,reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,IdentityFile=/home/user/.ssh/id_rsa wyng@sshserver:/home/wyng /home/wyng/wyng-backups
```

where the functional arch-init looked like:
`sudo wyng --local=qubes_dom0/pool00 --meta-dir=/var/lib/remote-test --dest=qubes://wyng-remote/home/wyng --subdir wyng-backups arch-init --compression bz2`

Question is: how to troubleshoot this identity management/wrong path settings if there is nothing given from `arch-init --debug` nor `send --debug` ? Feels like the command is just not having the identity added to connect to sshserver from wyng-remote. 

@tasket Any tips?

**Comment by tasket** [comment]
The trickiest part of the `arch-init` setup is ending `--dest` with an actual mountpoint. Otherwise it will say dest not ready. I think you'll need to move the user/wyng part of the path to subdir like `--subdir=user/wyng`.

Despite what it feels like, I think that's probably the reason. And I know that Wyng isn't being terribly helpful even in debug mode; that's on my v0.3 todo.

**Comment by tasket** [comment]
@tlaurion see above

**Comment by tlaurion** [comment]
@taskset
So in precedent example, successful arch-init looks like:
`sudo wyng --local=qubes_dom0/pool00 --meta-dir=/var/lib/test --dest=qubes-ssh://wyng-remote:wyng@sshserver/ --subdir=home/user/wyng/ arch-init --compression bz2`
