### ISSUE TITLE
Feature request: prune all backups but initial one

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#62]
Would complement #54 with #59 :)

**Comment by tasket** [comment]
A possible workaround is to delete all but the oldest session S_* dir, delete 'deltamap' file, and then change the 'last =' value in 'volinfo' to match 'first ='. After this, the user won't be able to `send` until they use `--remap`.

A roundabout way to do it is to `receive` the oldest session to a new LV, then replace the original LV with the new one, then `send`, then `prune` everything except the latest. This takes up to 2X as long to execute.

**Comment by tlaurion** [comment]
Well, I didn't explain myself really well, sorry.
The idea here would be to keep initial + last and prune all in between, so the user can always revert to initial image (emergency recovery) while having the last valid one.

**Comment by tasket** [comment]
In that case its pretty simple: Take the second session id and specify a range through to 'now' and do a regular prune. You can get a single-column list for parsing with `wyng -u list volname`.

**Comment by tasket** [comment]
BTW, I just noticed a formatting bug in the -u list output bc the 'S_' prefix should not be there.
