### ISSUE TITLE
Automatic .tick .tock lvmremove for volumes not found anymore

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#66]
@tasket :
As of right now, if a user removes volumes manually or per QubesOS tools, corresponding .tick LVMs are left behind, occupying same LVM space per snapshot.

Removing those left behind volumes with wyng at the same time it complains about them not being present:  `Warning: vm-personal-private does not exist!` would permit an easy way for the user to make sure LVM space is freed prior of restoring (receiving) volumes he intends to use more automatically.

**Comment by tasket** [comment]
I am leaning more toward requiring an affirmative action on the part of the user.

Eventually there will be a 'cleanup' type of command, but for now I'd prefer to keep this in the `delete` command.

**Comment by tlaurion** [comment]
@tasket not sure I understand the logic being implemented in delete, since we do not want to remove archives, just .tick and .tock for LVMs that do not exist anymore but for which backups existing or not is not relevant. (We just want to consolidate space for manually, externally deleted LVMs volumes)

**Comment by tasket** [comment]
This is being implemented now, not dependent on `delete` command/use case. But I want to get hardlinks issue squared away before posting it.

**Comment by tlaurion** [comment]
Will launch a verify on all volumes sent testing-dedup=5 with rc4pre2

**Comment by tlaurion** [comment]
Then will prune all old sessions

**Comment by tlaurion** [comment]
@tasket : no corruption. Even with backup having failed in the middle. Continued, pruned. and verified.
Seems all good.

**Comment by tasket** [comment]
@tlaurion This should be working the way you want now.

The latest commit today in rc5 branch can also re-purpose tock snapshots when necessary, and it now catches system signals (i.e. SIGTERM when system is shutting down) for write-finalization events. These two things together mean that --remap should be necessary far less often than it was.

**Comment by tlaurion** [comment]
Tried to use normally used commands on privacybeast use case on updating templates and synchronising Delta on dest wyng-backupvm with rc5 and failed, while it worked on master (rc4).

Will report back later

**Comment by tlaurion** [comment]
@tasket : testing the change with "Wyng 0.2.0_rc4pre2 20200627"

Use case problem:
I use two different meta-dir.

Main one knows mostly all the archives (list proposes them all). Some of the local volumes do not exist anymore, but are known from wyng-backups and listed when doing list. Those are the tick tock volumes that should be automatically deleted.

Remote one knows only about a subset of all available volumes. When running list on that meta-dir, wyng-backups removes all the tick tock snapshots, requiring the Main meta-dir to remap all the volumes.

Suggestion:
Only the volumes known from wyng for a meta-dir (default or specified) should have their tick tock volumes deleted. I would expect to be able to use both wyng instances without having to remap all volumes when calling one instance and then the other by sepecifying meta-dirs.

Makes sense?

**Comment by tasket** [comment]
I has wyng start to mark snapshots w the archive's UUID to potentially help in this situation.

But a fundamental problem is that metadir is now under user's control and wyng cannot guess as to whether a user will return to using any given archive, or if the archive has been abandoned. I think the best I can do for now is to limit `--clean` to deleting snapshots from only the currently processed archive and then say "BTW here is a list of snapshots from a different archive".

**Comment by tlaurion** [comment]
Each meta-dir contains a list of volumes supported by that wyng-backups instance.
@tasket : Why not delete tick and tock snapshots for volumes supported but not found anymore for that wyng-backups instance linked to specified/default mata-dir? That would be as simple as it can get. Of course, automated (cron) tasks will have to have --remap to make sure backups are made if voume is present while not mapped, even though implementing current proposition should deal with all side effects.

**Comment by tlaurion** [comment]
> I has wyng start to mark snapshots w the archive's UUID to potentially help in this situation.
Nice idea. If UUID is restored upon receive and shared across wyng-backups instances.

> 
> But a fundamental problem is that metadir is now under user's control and wyng cannot guess as to whether a user will return to using any given archive, or if the archive has been abandoned. 
Abandoned or not: this is where lies the problem. We do not want tick and tock snapshots for volumes that are not anymore visible for a wyng-backups instance (bound to its meta-dir). If the user receives a backup that was not found previously in pool but listed in achive.ini, tick should be created. wyng-backups invocation (default meta-dir or meta-dir specified) should remove tick and tock archives for volumes speicifed under archive.ini not found in pool.

> I think the best I can do for now is to limit `--clean` to deleting snapshots from only the currently processed archive and then say "BTW here is a list of snapshots from a different archive".
Agreed.

**Comment by tasket** [comment]
> @tasket : Why not delete tick and tock snapshots for volumes supported but not found anymore for that wyng-backups instance linked to specified/default meta-dir ?

Yes, thats basically what I'm proposing when I say "limit --clean to deleting snapshots from only the currently processed archive".

However, there should be some way to indicate to the user that still other snapshots exist. I must cover use cases where a user simply stops using archive XYZ, but doesn't want the snapshots to remain.

**Comment by tlaurion** [comment]
@tasket : modified https://github.com/tasket/wyng-backup/issues/66#issuecomment-660503072

**Comment by tasket** [comment]
> Nice idea. If UUID is restored upon `receive`/`send` and shared across wyng-backups instances. While I do not think it is pertinent to the issue i'm reporting here if that volume is shared between two wyng-backups meta-dir. Same logic in italic below should be applied in my humble opinion.

Two separate issues here:

1. Archive UUID is not like volume or snapshot UUIDs. Volume + snapshot UUIDs come from LVM currently and cannot be restored. Tagging snapshots with Session ID will happen in next update of rc5 to work around this.

2. A single volume cannot (currently) be tracked by more than one Wyng archive. Currently its not a supported use case. To support this, I would have to do something like embed the archive UUID in the snapshot volume name, or some other way to make multiple sets of snapshots unique. IMO its a hairy logistical problem.

**Comment by tlaurion** [comment]
@tasket Those .tick volumes are still present after a wyng-backup send when AppVM got deleted.

To replicate:
```
wyng-backup add vm-personal-private
wyng-backup send
qvm-remove personal
wyng-backup send
sudo lvs | grep vm-personal-private
```

vm-personal-private.tick is still present and was not autowiped.

**Comment by tlaurion** [comment]
@tasket 

Still have to clean for really old volumes manually

`ls /dev/qubes_dom0/ > ~/lvs; qvm-ls | awk -F " " {'print $1'}| tail -n +2 | while read line; do grep -v "$line" ~/lvs > ~/lvs.changed; mv ~/lvs.changed ~/lvs;done; cat ~/lvs; rm ~/lvs`

From given output, I had to sudo lvremove /dev/qubes_dom0/xxxx:
```
vm-fedora-30-dvm-private.tock
vm-fedora-30-root.tock
vm-Test-private.tock
```
That are old wyng created volumes for which no AppVM, nor original LVM existed, consuming unecessary space. Those tock volumes should be removed by wyng if original volumes are not found.

**Comment by tasket** [comment]
@tlaurion Sorry I didn't see this earlier...

Did you try using the `--clean` option? That is required to trigger the orphan snapshot removal.

**Comment by tlaurion** [comment]
@tasket added it to all my scripts, thanks! Not understanding why its not the default still, though!

**Comment by tasket** [comment]
Its not default because it can result in a still-present VM having its snapshot removed in error if that VM is undergoing a state transition (such as shutdown) at the same time. Similarly, non-Qubes transitions for volumes might cause the same problem.

This means its best to use `--clean` when you think subject VMs are in a stable state (running, or not running). Otherwise, Wyng will have to replace a missing snapshot on the next `send`, consuming a lot of extra disk IO and CPU.

If Qubes had a way of doing its LV transitions atomically, then it would be a different matter. But this may improve as system capabilities evolve.
