### ISSUE TITLE
Sync  -f does not work on RHEL/Centos 7

### ISSUE THREAD

**Issue by alvinstarr** [tasket/wyng-backup#69]
Possibly there needs to be a check for OS.

**Comment by tasket** [comment]
@alvinstarr I take it you mean the remote/destination system in your case is running RHEL/Centos 7.

That does seem a bit of a problem. I've seen older versions of `sync` that ignore all command line options, and this is still true of the current versions on *BSD. In this case specifying `-f` should not be a problem.

Somewhere along the line, GNU sync got to the point in RHEL 7 where it parsed options but still did not support `-f`.

Obvious workaround is to use `sync` without any options at least for certain versions. It may also be possible to group two `sync` commands together using `||` OR operator.

**Comment by tasket** [comment]
@alvinstarr See patched version in rc5 branch: https://github.com/tasket/wyng-backup/tree/rc5
