### ISSUE TITLE
Allow multiple source volume groups in an archive

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#76]
Support use cases where a user wants to add volumes from different vgs or even non-CoW storage to a single archive.

- [ ] ~~move vg/pool info into Volume()~~ (unnecessary)
- [x] process deltas with an outer loop keyed on the source vg

See notes below...

**Comment by boryeumao** [comment]
Tried poking around but hadn't found anything that may allow volumes from a second vg to go into the archive - Has this been implemented (in 0.3.1 20220804)? 

(A related question, on Qubes:  with "--local=qubes_dom0/vm-pool", I can add/send "root" to the archive, even though it resides in "qubes_dom0/root-pool".  Is this expected?  Thanks.)

**Comment by tasket** [comment]
@boryeumao @gdiShun There is a current option for supporting this use case: `--meta-dir`.  The meta-dir defaults to '/var/lib' but setting it to someplace else (say, a custom subdirectory of /var/lib or /var/cache, etc.) allows you to init and use other archives with different VGs and other parameters.

Status on this issue (multi VGs in a single archive) is still _unimplemented_ and TBH I'm not certain there is a great need for it.  However, there will be at least one additional way to use different archives/VGs in v0.04... archive location has already been de-linked from archive metadata itself, so if you imagine 'aname' becomes the archive UUID then that opens up possibilities. See issue #60

**Comment by boryeumao** [comment]
@tasket Thanks.  I will check out "--meta-dir", now that I understand what it is (should've checked the code more closely), and also v4 alpha.

If you could comment on the issue above on root being in a different t-pool from what is in "--local", that would be great.  Thx

**Comment by tasket** [comment]
@boryeumao You can mix tpools (of the same VG) in a single archive and it won't affect Wyng operations _except_ for `receive`.  So if this is a Qubes tpool setup the volumes will all be under 'qubes_dom0' VG, and that's how I use it BTW with root volume mixed in with VM volumes.

When using `receive` _and_ the volume doesn't already exist in the VG, Wyng will use the archive's pool setting to choose where to create the volume.  Probably this could be improved in the future by allowing users to specify `--local` for `receive` or something similar.

**Comment by boryeumao** [comment]
@tasket  Ah Yes precisely I wanted to be aware of anything to watch out for with mixing tpools. Thanks for clarifying.

**Comment by tasket** [comment]
The current v0.4 work in progress makes this issue largely moot.  The new version will accept any suitable `--local` option at runtime, so you can update/add to an archive from different sources very much like you would with `tar`.  The only limitation is that currently you can only specify one `--local` source at a time.
