### ISSUE TITLE
0.2.0rc9 wyng send "Error: Local and archive metadata differ."

### ISSUE THREAD

**Issue by Link42** [tasket/wyng-backup#77]
I'm having problem with the latest version doing send's.

```
# lvcreate -n wyntest -V 1G --thin lvmthin/thinpool
  Logical volume "wyntest" created.
# wyng-2021 send wyntest
Wyng 0.2.0rc9 20210511
Preparing snapshots...
Error: Local and archive metadata differ.
# wyng-2020 send wyntest
Wyng 0.2.0_rc7 20201214
Preparing snapshots...

Sending backup session 20210521-160210 to ssh://root@xxx.xxx.xxx.xxx
  100%      0.0M   |  wyntest
```

On 0.2.0_rc7 everything works fine, but not on rc9. Similar results on other commands working with the data.

**Comment by tasket** [comment]
@Link42 Thanks for the report. Try the rc10 update in master.

If you still get the error, run Wyng with the `--debug` option. At the end you should see a diff showing where the metadata problem is.

**Comment by Link42** [comment]
Awesome thats done the trick, rc10 working as intended.
