### ISSUE TITLE
Arch-init --from consuming all 2GB QubesOS's /tmp space when compressing decompressing

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#82]
At the compression finished state, 1.2Gb out of the 2GB available under QubesOS are consumed.
This explodes and fails at the moment of decompressing.

Is there a reason why the decompression is not occurring to final destination instead of in memory?
I see that if 1.2Gb is used out of the 2GB, there might be a problem later on if collection continues to grow.

Oupsies for large backups collection like mine at time of sync over a new QubesOS install.
Workarounds? Change of code possible? 

```
[user@dom0 tmp]$ time sudo /usr/sbin/wyng --meta-dir=/var/lib/2TB-wyng-backups --from=internal:/ --subdir=media/backups/QubesOS/ arch-init --debug
Wyng 0.3.0rc2 20210622

Metadata will be read from the archive;
Please check that the archive is in a trusted, secure condition!
Proceed? [y/N] y
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/wyng", line 2922, in <module>
    aset         = get_configs_remote()
  File "/usr/sbin/wyng", line 766, in get_configs_remote
    do_exec([[CP.tar,"-xzf",tmpdir+"/metadata.tgz"]], cwd=aset.path)
  File "/usr/sbin/wyng", line 1147, in do_exec
    if type(f) is not int: f.close()
OSError: [Errno 28] No space left on device

real	2m14.727s
user	2m10.179s
sys	0m10.062s
```

**Comment by tasket** [comment]
@tlaurion Perhaps /tmp was not the best place to put that. Unfortunately metadata won't be compressed until v0.4 is ready.

But note that if your archive had a smaller chunk size (i.e. the default) then your metadata would be 4X as large as it is now.

For short-term workaround, try expanding /tmp with:

```
mount -o remount,size=4G /tmp
```

**Comment by tasket** [comment]
@tlaurion See branch 'fix03'.
