### ISSUE TITLE
deltamap sometimes not found when trying to link to deltamap-tmp

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#84]
I do not know why I need to touch those empty files to get out of the error on `send --clean --remap`

```
1799 monitor_send
1340 update_delta_digest
No such file or directory deltamap -> deltamap-tmp 
```
Under local /var/lib/directory corresponding to a private and root volume that I'm not updating between sends (but with arch-init from between sends)

Use case, as you know, is to change meta-dir to backup volumes over two different archives. It seems that when I switch between the two meta-dir, something removes that deltamap. Why only for two specific volumes, I do not know.

**Comment by tlaurion** [comment]
@tasket 

Since i'm remapping drives and different archive states, i thought a `arch-init from` followed by a `monitor --remap --clean` would resolve the issue. Instead, now all my volumes lack of a deltamap file under meta-dir?

**Comment by tasket** [comment]
This is the current criteria in _prepare_snapshots()_ for creating a new _deltamap_ at the start of a `monitor` or `send`:
```
if lv_exists(vgname, snap1vol) and not exists(mapfile) \
and vol.last in l_vols[snap1vol].tags and "delta" not in l_vols[snap1vol].tags \
and l_vols[snap1vol].lv_uuid == vol.sessions[vol.last].uuid:
    # Latest session matches current snapshot; OK to make blank map.
    init_deltamap(vol, mapfile, vol.mapsize())
```

I'm guessing those volumes' snapshots have a different uuid tag or they are flagged as 'delta'. Also guessing after you `touch` _deltamap_ Wyng will say it "Removed mis-matched snapshot" or "Pairing snapshot".

There is probably more than one good way to deal with this situation so I'll need to give it some thought.

**Comment by tlaurion** [comment]
@tasket it says pairing snapshot where those are the same LVM volumes.

send with another meta-dir had 2 missing deltamap, where doing a monitor required all volumed to have deltamap touched manually.

**Comment by tasket** [comment]
@tlaurion Update posted

**Comment by tlaurion** [comment]
@tasket so from https://github.com/tasket/wyng-backup/commit/2bf4fc7b1938f74fcac7bcab11b5423f9c80d18e I understand that a arch-init from and a send should suffice from now on to fix deltamap file missing. I expect it to remap since UUIDs are not still not bound to LVM volumes but UUIDs having been generated per meta-dir, causing a re-pairing and remapping when switching between meta-dir representations of LVM volumes.

Test case:
1- Send to local qube wyng-archive (which is then pruned and dedeupped to keep only latest archive)
2- Send to remote sshfs qube wyng-archive (RW) (with different meta-dir), doing a arch-init from that qube first and then a send (without a monitor in between the two calls)
3- Do a remote qube wyng-archive sshfs (RO) arch-init from then try receive of a volume.
4- Do a local qube receive of a volume

Will report back

**Comment by tlaurion** [comment]
@tasket 

Doing a send after an arch-init from results in the following from the send command has the same new behavior then doing a monitor with --dedup --clean -remap :

```
Preparing snapshots
Pairing snapshot for vm-windows-10-standalone-private
Pairing snapshot for windows-10-standalone-root
Pairing snapshot for vm-work-private
```

Neither of the 3 volumes were modified from last send session.

Then:

```
line 2983 of module
  monitor_send (datavols, selected_vols, monitor_only=False
line 1808 in monitor_send
  dnew, dfree = send_volume(datavol, localtime, ses)tatgs, send_all=datavol in send_alls
line 1603 in send_volume
  tarf.add(pjoint(vol.name, os.path.basename(session.path)))
UnboundLocalError: Local variable tarf referenced before assignment
```

Wiped off all /tmp/wyng content.

Then, redid. Same error
cat /tmp/wyng/err.log first lines:
```
device-mapper: message ioctl on qubes_dom0-pool00-tpool failed: Invalid argument
Command failed
--+-- (lotsa)
then warnings saying sum of all thin volumes sizes exceeds the size blahblah
```

**Comment by tasket** [comment]
@tlaurion The error is from code that has to be re-written for v0.4. I'll have to do a workaround for now.

The log entries are normal, but the content of "/var/lib/wyng.backup/...../manifest" would be helpful to know. It should not be empty.

**Comment by tlaurion** [comment]
We are talking about a S_20210719-145133-tmp/manifest
`0 x000000007ffc0000`
info is the other file avail under that dir, which pointed to a backup did in late march, containing 8192 lines.

Anything else I can provide @tasket ?

**Comment by tasket** [comment]
@tlaurion This looks good. Thanks!

I'll have a fix tonight.

**Comment by tasket** [comment]
@tlaurion Updated at 648024e479864036d27a80670aa40dfda928e6e1

**Comment by tlaurion** [comment]
@tasket : Sending under way! Will report back after the sending operation is finished and I switch the meta-dir to do the local archive of the same LVMs

**Comment by tlaurion** [comment]
@tasket problem solved.
