### ISSUE TITLE
Reuse send "partial session dir" instead of deleting it

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#85]
As you know, sending over network comes with more delays and connection issues sometimes. SSHFS is more capricious, and having to resend changes, for example a Windows10 upgrade, can result easily into 8GB of changes in a send session.

If wyng was able to reuse previously incomplete send session instead of deleting it, it would be more resilient under ssh, qubes-ssh and qubes over sshfs modes.

**Comment by tasket** [comment]
Yes. But this is a duplicate of issue #15.
