### ISSUE TITLE
Incorrect arch-init args become sticky

### ISSUE THREAD

**Issue by timdiels** [tasket/wyng-backup#89]
After calling arch-init with a vg that does not exist:

    wyng --local=wrongvg/pool-correct --dest=internal:/my/mountpoint arch-init

it kept using the vg from the original command:

    wyng --local=qubes_dom0/pool-correct --dest=internal:/my/mountpoint arch-init

```
Traceback (most recent call last):
  File "/home/user/wyng/wyng", line 2914, in <module>
    aset             = get_configs()
  File "/home/user/wyng/wyng", line 743, in get_configs
    if aset.vgname:   lvm_meta_snapshot(aset, "release")
  File "/home/user/wyng/wyng", line 524, in lvm_meta_snapshot
    print(volgroups[arch.vgname])
KeyError: 'wrongvg'
```

I suspect it's due to the tmp archive.ini. I was able to work around it by deleting:

    rm -rf /var/lib/wyng.backup

**Comment by tasket** [comment]
Thanks! I'm working on a fix for this.

**Comment by tasket** [comment]
The best way to change the local storage parameters in v0.3 is to do `wyng arch-init --local=vg/pool --from=<dest spec>` which imports the archive settings with new local parameters.

However, if the current archive is empty/disposable then you can use `arch-delete` instead, then do a regular `arch-init` with the desired parameters.

**Comment by gdiShun** [comment]
Hi. I'm having a similar error where even `arch-delete` raises it.

```
➤sudo wyng --force arch-delete
Wyng 0.3.0rc2 20210622
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 2908, in <module>
    aset             = get_configs()
  File "/usr/local/bin/wyng", line 737, in get_configs
    if aset.vgname:   lvm_meta_snapshot(aset, "release")
  File "/usr/local/bin/wyng", line 520, in lvm_meta_snapshot
    for pool in volgroups[arch.vgname].poolnames if not pool and action == "release" \
KeyError: 'wtvg'
```
I created and mounted some test .imgs to see how exactly this would work. But now, those .imgs are long gone and I'm getting this error. The program is effectively unusable now. I noticed some files named after those test .imgs and their LVs in /etc/lvm. Would just deleting them do the trick, or is there some wyng-specific config file I could edit, or maybe a more proper way to remove those files?
