### ISSUE TITLE
Check for metadata synchronization

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#9]
- [x] When sparsebak starts any operations on the destination, it should check that the metadata on the source and destination are in sync.

   There is an *untrusted data* handling aspect to this, and it may be best to wait until encryption is integrated and can verify the destination manifests before adding this check.

- [ ] When receiving an older session, automatically resync the volume by digesting all the later manifests to the volume's deltamap. This will cause all the chunk addresses backed up since the selected session to be backed up again. (Currently the user receives a notice advising to use `--remap diff` after receiving the older session but this step can be saved.) Doing a differential save (always comparing blocks before writing) could be of value here.

- [x] When user has recovered archive metadata (e.g. after recovering or reinstalling their OS) using `--from arch-init`, intelligently re-check metadata to determine if its in sync with LVs and do a full remap only if absolutely necessary.

**Comment by tasket** [comment]
The best way to accurately track meta sync may be to name or tag the snap1/tick snapshots with the session date-time plus one flag indicating whether the snapshot has been rotated by `monitor`. If the tick snapshot date-time matches the latest session in the archive, and the rotation flag is 'no', then its in sync (therefore `--from arch-init` can create a blank deltamap without going through --remap).

**Comment by tlaurion** [comment]
In a stupid attempt to regain all needed LVM pool space and having too quickly reviewed the [code](https://github.com/tasket/wyng-backup/blob/master/wyng#L2005), I deleted all tick snapshots with lvremove, to launch wyng monitor and being told that the tick were not available and failing, instead of having that volume checked against voume data from backup against LVM directly.

redoing remap --diff manually!

**Comment by tasket** [comment]
Remember, if you're doing either `monitor` or `send` frequently, the space the snapshots use should be near zero.

**Comment by tasket** [comment]
Commit https://github.com/tasket/wyng-backup/commit/bfa3f0a45a49081a1a2a5903503267f26df6b594
This change can avoid the need for remapping when just a deltamap is missing. It can also remap multiple volume automatically during `send` startup if the user has specified `--remap`.

**Comment by tasket** [comment]
This is handled automatically now since `--remap` is the default action. It may not be as CPU-efficient as the idea in the second list item, but this use case should be infrequent enough for it to not matter.
