### ISSUE TITLE
04alpha --arch-deduplicate fails

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#98]
line 2168 NoneTyp dedup.lst.gz is not callable

**Comment by tlaurion** [comment]
Sending clean archive with default parameters with --dedup works, though.

**Comment by tlaurion** [comment]
@tasket same applies to 03fix in this case!

**Comment by tasket** [comment]
Appears to be working now for 04alpha.  Recently changed `arch-deduplicate` to not require `--dedup` option.

**Comment by tasket** [comment]
Currently working for me with 0.3.1 (master) and 0.4alpha2.
